import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Antonio, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./providers/ConvexClientProvider";
import { ThemeProvider } from "./providers/ThemeProvider";
import { InitUser } from "@/components/auth/InitUser";
import { Toaster } from "sonner";
import "./globals.css";

// Temporarily disable auth for testing
const DISABLE_AUTH = process.env.NEXT_PUBLIC_DISABLE_AUTH === "true";

// Creative Studio Warmth typography
const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const antonio = Antonio({
  variable: "--font-display",
  subsets: ["latin"],
  weight: "700",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = (
    <html lang="en" className={`${plusJakartaSans.variable} ${antonio.variable}`} suppressHydrationWarning>
      <body className={`${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <ConvexClientProvider>
            {!DISABLE_AUTH && <InitUser />}
            {children}
            <Toaster position="bottom-right" />
          </ConvexClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );

  if (DISABLE_AUTH) {
    return content;
  }

  return <ClerkProvider>{content}</ClerkProvider>;
}
